name: parameterized workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Parameter' 
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  App1:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App1
      if: github.event.inputs.name == 'one'
      run: echo "Hello ${{ github.event.inputs.name }}"
      if: false == github.event.inputs.name == 'Two'
      run: echo "Hello ${{ github.event.inputs.name }}" 
    
