name: parameterized workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'App1' 
        required: true
        description: 'App2'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  App1:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App1
      if: github.event.inputs.name == 'App1'
      run: echo "Hello ${{ github.event.inputs.name }}"
  App2:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App2
      if: github.event.inputs.name == 'App2'
      run: echo "Hello ${{ github.event.inputs.name }}"  
    
