name: parameterized workflow
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Select Application to Deploy'
        default: 'App1'
        required: true
      name:
        description: 'Person to greet'
        required: true  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  App1:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App1
      run: echo "Hello ${{ github.event.inputs.name }}"
